N_Queens_problem/N_Queens_problem/Controllers/LocalSearchAlgorithmsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ArtificialIntelligence.Models;
using ArtificialIntelligence.Models.Algorithms;

namespace ArtificialIntelligence.Controllers
{
    public class LocalSearchAlgorithmsController : Controller
    {
        public IActionResult Index(int size = 4)
        {
            NQueensProblem nQueensProblem = new NQueensProblem(size);

            nQueensProblem.SetRandomBoardState();
            nQueensProblem.DoAlgorithm(); // just heuristic result

            var board = nQueensProblem.GetResultBoard();

            board.CheckIfProblemSolved();

            return View(board);
        }

        [HttpPost]
        public IActionResult ChangeBoardgameSize(IFormCollection formCollection)
        {
            int size = int.Parse(formCollection["SizeSelect"]);

            NQueensProblem nQueensProblem = new NQueensProblem(size);

            nQueensProblem.SetRandomBoardState();
            nQueensProblem.DoAlgorithm(); // just heuristic result

            var board = nQueensProblem.GetResultBoard();
            board.CheckIfProblemSolved();

            return View("Index", board);
        }

        [HttpPost]
        public IActionResult DoAlgorithm(IFormCollection formCollection)
        {
            NQueensProblem nQueensProblem = new NQueensProblem();

            var algorithmName = formCollection["AlgorithmSelect"];

            switch (algorithmName)
            {
                case "Hill Climbing":
                    try // taking parameters from View and set it
                    {
                        var maximumNumberOfSteps = uint.Parse(formCollection["MaxSteps"]);
                        nQueensProblem.SetMaximumNumberOfSteps(maximumNumberOfSteps);
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine("Exception message: {0}", e.Message);
                    }
                    nQueensProblem.SetAlgorithm(new HillClimbingAlgorithm());
                    break;

                case "Simulated Annealing":
                    try // taking parameters from View and set it
                    {
                        var startingTemperature = int.Parse(formCollection["StartingTemperature"]);
                        nQueensProblem.SetStartingTemperature(startingTemperature);
                        var coolingFactor = int.Parse(formCollection["CoolingFactor"]);
                        nQueensProblem.SetCoolingFactor(coolingFactor);
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine("Exception message: {0}", e.Message);
                    }
                    nQueensProblem.SetAlgorithm(new SimulatedAnnealingAlgorithm());
                    break;

                case "Local Beam Search":
                    try // taking parameters from View and set it
                    {
                        var maximumNumberOfSteps = uint.Parse(formCollection["MaxSteps"]);
                        nQueensProblem.SetMaximumNumberOfSteps(maximumNumberOfSteps);
                        var numberOfStates = uint.Parse(formCollection["NumberOfStates"]);
                        nQueensProblem.SetNumberOfStates(numberOfStates);
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine("Exception message: {0}", e.Message);
                    }
                    nQueensProblem.SetAlgorithm(new LocalBeamSearchAlgorithm());
                    break;
                case "Genetic":
                    try // taking parameters from View and set it
                    {
                        var sizeOfSingleGeneration = int.Parse(formCollection["SizeOfSingleGeneration"]);
                        nQueensProblem.SetSizeOfSingleGeneration(sizeOfSingleGeneration);

                        var percentOfElitism = int.Parse(formCollection["PercentOfElitism"]);
                        nQueensProblem.SetPercentOfElitism(percentOfElitism);

                        var crossoverProbability = int.Parse(formCollection["CrossoverProbability"]);
                        nQueensProblem.SetCrossoverProbability(crossoverProbability);

                        var mutationProbability = int.Parse(formCollection["MutationProbability"]);
                        nQueensProblem.SetMutationProbability(mutationProbability);

                        var numberOfGenerations = int.Parse(formCollection["NumberOfGenerations"]);
                        nQueensProblem.SetNumberOfGenerations(numberOfGenerations);
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine("Exception message: {0}", e.Message);
                    }
                    nQueensProblem.SetAlgorithm(new GeneticAlgorithm());
                    break;
                default:
                    nQueensProblem.SetAlgorithm(new HillClimbingAlgorithm());
                    break;
            }

            nQueensProblem.DoAlgorithm();

            var resultBoard = nQueensProblem.GetResultBoard();
            resultBoard.CheckIfProblemSolved();

            return View("Index", resultBoard);
        }
    }
}

N_Queens_problem/N_Queens_problem/Controllers/SymbolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ArtificialIntelligence.Controllers
{
    public class SymbolController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

N_Queens_problem/N_Queens_problem/Controllers/TicTacToeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArtificialIntelligence.Models.TicTacToe;
using ArtificialIntelligence.Models.TicTacToe.Algorithm;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ArtificialIntelligence.Controllers
{
    public class TicTacToeController : Controller
    {
        public IActionResult Index()
        {
            TicTacToe ticTacToe = TicTacToe.Instance;

            ticTacToe.ClearBoard();

            TicTacToeBot bot = TicTacToeBot.Instance;
            TicTacToeUser user = TicTacToeUser.Instance;
            bot.SetTicTacToe(ticTacToe);
            user.SetTicTacToe(ticTacToe);

            // switch starting
            if(ticTacToe.IsPlayerStarting == true)
            {
                ticTacToe.IsPlayerStarting = false;
                // bot first move
                AlphaBetaPruning alphaBetaPruning = new AlphaBetaPruning(ticTacToe.ticTacToeBoard, ticTacToe.Level);
                Tuple<int, int> xy = alphaBetaPruning.BestMove();
                bot.MakeMove(xy.Item1, xy.Item2);
            }
            else
            {
                ticTacToe.IsPlayerStarting = true;
            }

            return View(ticTacToe);
        }

        [HttpPost]
        public IActionResult NextMove(IFormCollection formCollection)
        {
            TicTacToe ticTacToe = TicTacToe.Instance;
            TicTacToeChecker ticTacToeChecker = new TicTacToeChecker();
            TicTacToeBot bot = TicTacToeBot.Instance;
            TicTacToeUser user = TicTacToeUser.Instance;

            // setting level
            ticTacToe.Level = int.Parse(formCollection["Level"]);
            
            string place = formCollection["Button"];
            int userX = int.Parse(place[0].ToString());
            int userY = int.Parse(place[1].ToString());

            // user
            user.MakeMove(userX, userY);
            //
            ticTacToeChecker.CheckGameStatus(ticTacToe);

            if(ticTacToe.GameStatus == GameStatus.InProgress)
            {
                // bot
                AlphaBetaPruning alphaBetaPruning = new AlphaBetaPruning(ticTacToe.ticTacToeBoard, ticTacToe.Level);
                Tuple<int, int> xy = alphaBetaPruning.BestMove();
                bot.MakeMove(xy.Item1, xy.Item2);
                //
                ticTacToeChecker.CheckGameStatus(ticTacToe);

                if (ticTacToe.GameStatus != GameStatus.InProgress)
                {
                    ticTacToeChecker.CheckGameStatusAndGivePoint(ticTacToe);
                }
            }
            else
            {
                ticTacToeChecker.CheckGameStatusAndGivePoint(ticTacToe);
            }

            return View("Index", ticTacToe);
        }
    }
}

N_Queens_problem/N_Queens_problem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    @RenderSection("Scripts", required: false)

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LocalSearchAlgorithms" asp-action="Index" style="margin-left: 50px; margin-right: 30px;">N Queens Problem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TicTacToe" asp-action="Index" style="margin-right: 30px;">Tic-Tac-Toe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Symbol" asp-action="Index" style="margin-right: 30px;">Symbol Guessing</a>
                        </li>
                        @* MORE NAV ITEMS HERE*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <footer class="border-top footer text-muted">
        <div class="container">
            Mateusz Piwowarski
            <a style="text-align: right; float: right;" href="https://github.com/matpiwowarski/Local-Search-Algorithms" title="Github">Github</a>
        </div>
    </footer>
</body>
</html>